### ISSUE TITLE
Protocol "https" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by aybakana** [ethz-asl/gflags_catkin#15] opened 2019-02-05 07:02 UTC
> -- downloading...
>      src='https://github.com/gflags/gflags/archive/v2.2.1.zip'
>      dst='/home/roblab/catkin_ws/build/gflags_catkin/gflags_src-prefix/src/v2.2.1.zip'
>      timeout='none'
> CMake Error at gflags_src-stamp/download-gflags_src.cmake:27 (message):
>   error: downloading 'https://github.com/gflags/gflags/archive/v2.2.1.zip'
>   failed
> 
>     status_code: 1
>     status_string: "Unsupported protocol"
>     log: Protocol "https" not supported or disabled in libcurl
> 
>   Closing connection -1

I have this issue even if I upgraded curl.

**Comment by HannesSommer** [comment] 2019-02-05 08:37
The problem is probably not curl but libcurl. Please check whether you installed either the gnutls or the openssl version of libcurl. If that doesn't help please post the output of `ldd $(which curl)` (assuming Linux) and the OS + version you are using.

**Comment by aybakana** [comment] 2019-02-11 06:36
This is the output,

> 	linux-vdso.so.1 =>  (0x00007ffdbb9b2000)
	libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007fbe18ba5000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fbe1898c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbe1876e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbe183a5000)
	librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007fbe1818b000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fbe17f2c000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fbe17b4f000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007fbe178fe000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007fbe176ef000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbe18e1e000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007fbe17430000)
	libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007fbe171b0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbe16fac000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fbe16d91000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007fbe16b76000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007fbe16938000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fbe16724000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fbe164e2000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fbe162dd000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007fbe160d4000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007fbe15e4c000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007fbe15bab000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fbe159a7000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007fbe15774000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007fbe1555f000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fbe15357000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007fbe1512e000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007fbe14f20000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007fbe14cd7000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fbe14a1e000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fbe147e5000)
I tried to install libcurl with openssl but still I get the same error.

**Comment by HannesSommer** [comment] 2019-02-11 13:28
Thanks. Ah, actually we needed `ldd $(which cmake)`. (I overlooked that cmake links to libcurl -- sorry). Probably cmake is linked to a non ssl capable version of

**Comment by aybakana** [comment] 2019-02-13 11:07
The output:
> 	linux-vdso.so.1 =>  (0x00007ffd2d941000)
> 	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f5a275aa000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5a273a6000)
> 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5a270a2000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5a26d9c000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5a26b86000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5a267bd000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f5a277dd000)

Sorry for late reply.

**Comment by caomuqing** [comment] 2019-03-29 15:15
i am facing the same issue here, `ldd $(which cmake)` gives:
```
	linux-vdso.so.1 =>  (0x00007ffe63eca000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007feda50e6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007feda4d64000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007feda4a5b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007feda4845000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007feda447b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007feda52ea000)
```
any solution on this error?

**Comment by caomuqing** [comment] 2019-03-31 12:04
This is solved by recompile my version of cmake module with --system-curl option:
```
git clone -b v3.5.2 https://cmake.org/cmake.git cmake
cd cmake
./bootstrap --system-curl
make
sudo make install
```
Hope this helps others who have this trouble.

**Comment by HannesSommer** [comment] 2019-03-31 13:54
Thanks @caomuqing , for your solution! It seems indeed you two are on systems for which the packaged cmake comes statically linked to a version of libcurl with missing or disabled https support. Recompilation is one way to work around this. Maybe there are easier ways, too , such as other binary distributions of cmake that do not have this shortcoming.

Github does not provide http (i.e. non-TLS) access to these files. Therefore there isn't much this library could do differently regarding this issue. 'Closing it therefore. 

 @caomuqing , @aybakana could you please provide which OS (version) you were experiencing this problem on? (for those that might run into a similar problem).

**Closed by HannesSommer** 2019-03-31 13:54 UTC

**Comment by JoeREISys** [comment] 2022-05-22 23:08
> This is solved by recompile my version of cmake module with --system-curl option:
> 
> ```
> git clone -b v3.5.2 https://cmake.org/cmake.git cmake
> cd cmake
> ./bootstrap --system-curl
> make
> sudo make install
> ```
> 
> Hope this helps others who have this trouble.

How did people code before Github and SO?!? Fixed issue, thanks!

**Comment by empowerszc** [comment] 2023-05-22 05:00
Recently i meet this problem too, thanks for your inspirational Ideas. I solve this problem by using latest cmake. And I don't find the obvious link to curl by  `ldd $(which cmake)`.
